language: perl6
perl6:
  - latest
  - 2016.04
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libogg-dev libvorbis-dev
install:
  - rakudobrew build-panda
  - zef install JSON::Fast
  - zef install Test::META
  - zef install --deps-only .
branches:
  only:
    - master
